// Note: TrustedIssuerLocalDto will be generated by drift_dev
// Using dynamic temporarily until code generation
/// Repository for managing trusted issuers
abstract class TrustRepository {
  /// Add a trusted issuer
  Future<void> addTrustedIssuer({
    required String issuerId,
    required String name,
    required String publicKeyJwk,
    required String source,
  });

  /// Remove a trusted issuer
  Future<void> removeTrustedIssuer(String issuerId);

  /// Get all trusted issuers
  // Note: Return type will be List<TrustedIssuerLocalDto> after drift_dev generates code
  Future<List<dynamic>> getTrustedIssuers();

  /// Get a trusted issuer by ID
  // Note: Return type will be TrustedIssuerLocalDto? after drift_dev generates code
  Future<dynamic> getTrustedIssuer(String issuerId);
}


