import 'dart:convert';
import 'package:jose/jose.dart';
import 'package:health_wallet/features/smart_health_share/domain/shared/repositories/trust_repository.dart';
import 'package:health_wallet/features/smart_health_share/domain/shared/services/jws_signing_service.dart';
import 'package:health_wallet/features/smart_health_share/domain/shared/services/trust_manager_service.dart';
import 'package:injectable/injectable.dart';

@Injectable(as: TrustManagerService)
class TrustManagerServiceImpl implements TrustManagerService {
  final TrustRepository _trustRepository;
  final JWSSigningService _jwsSigningService;

  TrustManagerServiceImpl(this._trustRepository, this._jwsSigningService);

  @override
  Future<void> addTrustedIssuer({
    required String issuerId,
    required String name,
    required JsonWebKey publicKey,
    required String source,
  }) async {
    final publicKeyJwk = jsonEncode(publicKey.toJson());
    await _trustRepository.addTrustedIssuer(
      issuerId: issuerId,
      name: name,
      publicKeyJwk: publicKeyJwk,
      source: source,
    );
  }

  @override
  Future<void> removeTrustedIssuer(String issuerId) async {
    await _trustRepository.removeTrustedIssuer(issuerId);
  }

  @override
  Future<List<TrustedIssuerInfo>> getTrustedIssuers() async {
    // Note: TrustedIssuerLocalDto will be generated by drift_dev
    // Using dynamic cast temporarily until code generation
    final issuers = await _trustRepository.getTrustedIssuers() as dynamic;
    return (issuers as List).map((issuer) {
      // Access properties using dynamic - will be properly typed after drift_dev
      return TrustedIssuerInfo(
        issuerId: (issuer as dynamic).issuerId as String? ?? '',
        name: (issuer as dynamic).name as String? ?? '',
        source: (issuer as dynamic).source as String? ?? '',
        addedAt: (issuer as dynamic).addedAt as DateTime? ?? DateTime.now(),
      );
    }).toList();
  }

  @override
  Future<String?> verifySignature({
    required String compactJws,
  }) async {
    // Extract issuer ID from JWT
    final issuerId = extractIssuerId(compactJws);
    if (issuerId == null) {
      return null;
    }

    // Get trusted issuer
    final trustedIssuer = await _trustRepository.getTrustedIssuer(issuerId);
    if (trustedIssuer == null) {
      return null;
    }

    // Parse public key
    try {
      final publicKeyJson = jsonDecode(trustedIssuer.publicKeyJwk) as Map<String, dynamic>;
      final publicKey = JsonWebKey.fromJson(publicKeyJson);

      // Verify signature
      final isValid = await _jwsSigningService.verifyJwt(
        compactJws: compactJws,
        publicKey: publicKey,
      );

      return isValid ? issuerId : null;
    } catch (e) {
      return null;
    }
  }

  @override
  String? extractIssuerId(String compactJws) {
    try {
      // Parse JWT header to get kid
      final parts = compactJws.split('.');
      if (parts.length != 3) {
        return null;
      }

      // Decode header
      final headerBase64 = parts[0];
      final padded = _addPadding(headerBase64);
      final headerBytes = base64Url.decode(padded);
      final headerJson = utf8.decode(headerBytes);
      final header = jsonDecode(headerJson) as Map<String, dynamic>;

      // Extract kid (key ID) - this is used as issuer ID
      return header['kid'] as String?;
    } catch (e) {
      return null;
    }
  }

  String _addPadding(String base64) {
    final remainder = base64.length % 4;
    if (remainder == 0) {
      return base64;
    }
    return base64 + '=' * (4 - remainder);
  }
}


